# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import sys
import requests

import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QObject, QCoreApplication
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QApplication, QMainWindow, QLineEdit, QDialog


class Ui_Form(QDialog):
    # 传递选人信息的信号
    heroSignal = pyqtSignal(dict)
    closeSignal = pyqtSignal()
    hero_head_info = {}

    def __init__(self, index):
        super().__init__()
        self.index = index
        with open('hero_head_info.json') as f:
            self.hero_head_info = json.load(f)
            print(self.hero_head_info)
        print(self.index)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 1000)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 960, 960))
        self.tabWidget.setObjectName("tabWidget")

        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("战士")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("法师")

        self.currentChoose = QtWidgets.QLabel(Form)
        self.currentChoose.setGeometry(QtCore.QRect(200, 300, 80, 20))
        self.currentChoose.setText("当前英雄")
        self.confirmButton = QtWidgets.QPushButton(Form)
        self.confirmButton.setGeometry(QtCore.QRect(300, 300, 80, 30))
        self.confirmButton.clicked.connect(self.sendHeroSignal)
        self.confirmButton.setText("确认选择")

        self.pushButton_1 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_1.setGeometry(QtCore.QRect(46, 40, 100, 100))
        self.pushButton_1.setObjectName("廉颇")
        img_path = self.hero_head_info[self.pushButton_1.objectName()]  # 图片路径
        res = requests.get(img_path)
        img = QImage.fromData(res.content)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap.fromImage(img))
        self.pushButton_1.setIcon(icon)
        self.pushButton_1.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_1.clicked.connect(lambda: self.writeCurrentChoose(name=self.pushButton_1.objectName()))

        img_path = "touxiang/{}.jpg".format()
        self.pushButton_1

        self.label_1 = QtWidgets.QLabel(self.tab_1)
        self.label_1.setGeometry(QtCore.QRect(81, 150, 30, 20))
        self.label_1.setObjectName("label_1")

        self.pushButton_2 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_2.setGeometry(QtCore.QRect(238, 40, 100, 100))
        self.pushButton_2.setObjectName("吕布")
        img_path = self.hero_head_info[self.pushButton_2.objectName()]  # 图片路径
        res = requests.get(img_path)
        img = QImage.fromData(res.content)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap.fromImage(img))
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_2.clicked.connect(lambda: self.writeCurrentChoose(name=self.pushButton_2.objectName()))

        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(273, 150, 70, 20))
        self.label_2.setObjectName("label_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_3.setGeometry(QtCore.QRect(238, 40, 100, 100))
        self.pushButton_3.setObjectName("吕布")
        img_path = self.hero_head_info[self.pushButton_2.objectName()]  # 图片路径
        res = requests.get(img_path)
        img = QImage.fromData(res.content)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap.fromImage(img))
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_3.clicked.connect(lambda: self.writeCurrentChoose(name=self.pushButton_2.objectName()))

        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(273, 150, 70, 20))
        self.label_3.setObjectName("label_2")





        self.tabWidget.addTab(self.tab_1, "")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.closeSignal.connect(Form.close)

    def writeCurrentChoose(self, name: str):
        self.currentChoose.setText(name)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "战士"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "法师"))

        self.label_1.setText(_translate("Form", "廉颇"))

        self.label_2.setText(_translate("Form", "吕布"))

    def sendHeroSignal(self):
        name = self.currentChoose.text()
        address = self.hero_head_info[name]
        context = {'path': address, 'index': self.index}
        self.heroSignal.emit(context)
        self.closeSignal.emit()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    Form = QDialog()
    ui = Ui_Form(1)
    ui.setupUi(Form)
    Form.show()
    # child_window = Ui_Form(1)
    # child_window.show()
    sys.exit(app.exec_())
